[[nodes]]
id = 0
host = "127.0.0.1"
port = 8080
byzantine = false

[[nodes]]
id = 1
host = "127.0.0.1"
port = 8081
byzantine = false

[[nodes]]
id = 2
host = "127.0.0.1"
port = 8082
byzantine = true     # 👈 this node will misbehave

[[nodes]]
id = 3
host = "127.0.0.1"
port = 8083
byzantine = false